create-session:
  function: ./create-session.js
  web: 'yes'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: false
    final: true
validate-payment:
  function: ./validate-payment.js
  web: 'yes'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: false
    final: true
