operations:
   view:
      - type: web
        impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    starter-kit:
      license: Apache-2.0
      actions:
        # Please DO NOT DELETE this action; future functionalities planned for upcoming starter kit releases may stop working.
        info:
          function: actions/starter-kit-info/index.js
          web: 'yes'
          runtime: nodejs:20
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
    webhook:
      license: Apache-2.0
      actions:
        $include: ./actions/webhook/actions.config.yaml
    order-commerce:
      license: Apache-2.0
      actions:
        $include: ./actions/order/commerce/actions.config.yaml
    order-backoffice:
      license: Apache-2.0
      actions:
        $include: ./actions/order/external/actions.config.yaml
    spa:
      license: Apache-2.0
      actions:
        $include: ./actions/spa/actions.config.yaml
    emea_partner_days_2025:
        license: Apache-2.0
        actions:
          $include: ./actions/data/actions.config.yaml
